name: assignment_2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.11
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  flutter_styled_toast: ^2.2.1
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3


flutter:
  uses-material-design: true